/* Build step for the Capacitor shell + demo page.
   1. Copies the web app into www/ (Capacitor's webDir).
   2. Regenerates demo.html from index.html so the two never drift.
   Run via: npm run build */
import { rmSync, mkdirSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const www = join(root, "www");

/* ---- 1. www/ for the native shell ---- */
const ASSETS = [
  "index.html",
  "manifest.webmanifest",
  "sw.js",
  "icon-192.png",
  "icon-512.png",
  "apple-touch-icon.png"
];
rmSync(www, { recursive: true, force: true });
mkdirSync(www);
for (const f of ASSETS) copyFileSync(join(root, f), join(www, f));
console.log(`www/ built (${ASSETS.length} files)`);

/* ---- 2. demo.html = index.html + first-open seed ---- */
const seed = `<script>
/* DEMO BUILD — the only differences from index.html: this seed block and a
   separate storage key, so the demo NEVER touches (or shows) a family's real
   diary in the same browser. Regenerated by scripts/build.mjs — edit there. */
(function(){
  try{
    if (localStorage.getItem("peds-sleep-diary-demo-v1")) return;
    var today = new Date();
    function dAgo(k){
      var t = new Date(today.getFullYear(), today.getMonth(), today.getDate()-k);
      return t.getFullYear()+"-"+String(t.getMonth()+1).padStart(2,"0")+"-"+String(t.getDate()).padStart(2,"0");
    }
    var demo = [
      {lo:"19:45",on:"20:10",wk:"06:20",ob:"06:35",aw:[{time:"01:30",dur:20,help:"room"}],naps:[{inBed:"12:40",asleep:"12:55",woke:"14:10",out:"14:15"}]},
      {lo:"20:05",on:"20:50",wk:"06:05",ob:"06:25",aw:[{time:"00:45",dur:15,help:"fed"},{time:"03:20",dur:25,help:"bed"}],naps:[{inBed:"13:00",asleep:"13:10",woke:"14:20",out:"14:25"}]},
      {lo:"19:50",on:"20:15",wk:"06:30",ob:"06:40",aw:[],naps:[{inBed:"12:30",asleep:"12:50",woke:"13:55",out:"14:00"}]},
      {lo:"20:30",on:"21:15",wk:"06:15",ob:"06:45",aw:[{time:"02:10",dur:35,help:"bed"}],naps:[]},
      {lo:"19:40",on:"20:00",wk:"06:25",ob:"06:35",aw:[{time:"01:00",dur:10,help:"none"}],naps:[{inBed:"12:45",asleep:"13:00",woke:"14:30",out:"14:35"}]},
      {lo:"20:00",on:"20:35",wk:"05:50",ob:"06:20",aw:[{time:"23:50",dur:15,help:"room"},{time:"03:40",dur:20,help:"room"}],naps:[{inBed:"13:10",asleep:"13:25",woke:"14:15",out:"14:20"}]},
      {lo:"19:55",on:"20:20",wk:"06:10",ob:"06:30",aw:[],naps:[{inBed:"12:50",asleep:"13:05",woke:"14:25",out:"14:30"}]}
    ];
    var entries = {};
    demo.forEach(function(d,i){
      var date = dAgo(demo.length - i);
      entries[date] = { date:date, lightsOut:d.lo, onset:d.on, wake:d.wk, outOfBed:d.ob,
        awakenings:d.aw, naps:d.naps, notes: i===3 ? "Skipped nap at daycare; bedtime battle" : "" };
    });
    var state = { version:2, activeChild:"c1",
      children:{ c1:{ settings:{ initials:"Demo", ageBand:"toddler" }, entries:entries } },
      meta:{ lastBackupAt:null }, drive:{ fileId:null, lastBackupAt:null } };
    localStorage.setItem("peds-sleep-diary-demo-v1", JSON.stringify(state));
  }catch(e){}
})();
</${"script"}>
`;

const src = readFileSync(join(root, "index.html"), "utf8");
const marker = '<script>\n"use strict";';
if (!src.includes(marker)) throw new Error("main script marker not found in index.html");
const demoHtml = src
  .replace("<title>Pediatric Sleep Diary</title>", "<title>Pediatric Sleep Diary — Demo</title>")
  .replace('const STORE_KEY = "peds-sleep-diary-v1";', 'const STORE_KEY = "peds-sleep-diary-demo-v1";')
  .replace(marker, seed + marker);
if (!demoHtml.includes("peds-sleep-diary-demo-v1")) throw new Error("demo storage-key rewrite failed");
writeFileSync(join(root, "demo.html"), demoHtml);
console.log("demo.html regenerated");
